### ISSUE TITLE
possible to get only whole numbers with match_restrictions?

### ISSUE THREAD

**Issue by smartie5** [markvanderloo/rspa#3]
Hello! 
Is there the possibility to use the function match_restrictions and tell R that I just want to get whole numbers out? Or do you know any other function to use in this case?
I have a dataframe and an edit rule like 
```ruby
df <- data.frame(a=3, b=8, x=10)
rule <- validator(a+b==x)
```
and would like R to change a or b but keep whole numbers.

**Comment by markvanderloo** [comment]
Hi Smartie5,

You can try the following:

```r
df %>% 
  errorlocate::replace_errors(rule) %>% 
 deductive::impute_lr(rules)
```
This
1. Removes faulty values (makes them `NA`) based on Fellegi and Holt's principle (change as little variables as necessary)
2. Tries to impute a better value.

There is no strict guarantee that the imputed values are whole numbers.


The algorithm behind `match_restrictions`  is based on real numbers. It projects the [some part of] the record on the convex cone defined by a set of (in)equality restrictions.

In general, restricting such problems to integers creates some limitations on the restrictions you are allowed to consider. To be precise, the matrix *A* in a restriction set *Ax = b* has to be totally unimodular (each minor *M* of *A* must have det(*M*) in {-1,0,1}).

**Comment by smartie5** [comment]
Yes, that works for my data and is the step I was looking for. Thank you
